// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"ac-project/api/internal/service/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitalizeUserService() (user.Service, error) {
	userClientSet := newClients()
	userRepoSet := newUserRepos(userClientSet)
	service := newService(userRepoSet)
	return service, nil
}

// wire.go:

var userSet = wire.NewSet(
	newService,
	newUserRepos,
	newClients,
)
