// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"ac-project/api/internal/storage/firebase"
	"ac-project/api/internal/storage/mysql"
	"context"
)

// Injectors from wire.go:

func InitializeUserRepository(contextContext context.Context) (mysql.UserRepository, error) {
	db := ConnectDb()
	userRepository := mysql.NewRepository(db)
	return userRepository, nil
}

func InitializeAuthHandler(contextContext context.Context) (firebase.AuthHandler, error) {
	client := newFirebaseClient()
	authHandler := firebase.NewAuthHandler(client)
	return authHandler, nil
}
